version: '3.7'
services:
  webapp:
    container_name: webapp
    environment:
      - DEBUG=1
    build:
      context: .
      target: development
      args:
        - PROJECT_PATH=${PROJECT_PATH}
    image: webapp:latest
    volumes:
      - .:/gopath/src/project
